// Generated by CoffeeScript 1.7.1
(function() {
  var PSD, Rectangle;

  PSD = Framer.Importer.load("imported/google-reel");

  common.storeOriginal(PSD);

  Layer.prototype.fadeOut = function(delay) {
    return this.animate({
      properties: {
        opacity: 0
      },
      curve: 'ease-in',
      delay: delay
    });
  };

  Rectangle = new Layer({
    width: 400,
    height: 400,
    backgroundColor: "#fff",
    shadowY: 2,
    shadowBlur: 5,
    borderRadius: "6px"
  });

  Rectangle.superLayer = PSD.container;

  Rectangle.scale = 0.01;

  Rectangle.center();

  Rectangle.animate({
    properties: {
      scale: 1
    },
    time: 0.2
  });

}).call(this);
