// Generated by CoffeeScript 1.7.1
(function() {
  var PSD, afterRotate, background, createRectangle, rectangle, rectangle2, rectangle3, rectangle4;

  PSD = Framer.Importer.load("imported/google-reel");

  common.storeOriginal(PSD);

  Layer.prototype.move = function(x, y, curve, time) {
    curve = curve || "spring(200, 20, 10)";
    time = time || 0.2;
    return this.animate({
      properties: {
        x: this.x + x,
        y: this.y + y
      },
      curve: curve,
      time: time
    });
  };

  Layer.prototype.fadeOut = function(delay) {
    return this.animate({
      properties: {
        opacity: 0
      },
      curve: 'ease-in',
      delay: delay,
      time: 0.2
    });
  };

  Layer.prototype.fadeIn = function(delay) {
    return this.animate({
      properties: {
        opacity: 1
      },
      curve: 'ease-in',
      delay: delay,
      time: 0.2
    });
  };

  PSD.container.brightness = 0;

  PSD.container.animate({
    properties: {
      brightness: 100
    },
    curve: "linear",
    time: 0.5
  });

  background = new BackgroundLayer({
    backgroundColor: "rgba(77, 208, 225, 1.00)"
  });

  createRectangle = function() {
    var layer;
    layer = new Layer({
      width: 400,
      height: 400,
      backgroundColor: "#fff",
      shadowY: 2,
      shadowBlur: 5,
      borderRadius: "6px",
      opacity: 0
    });
    layer.shadowColor = "rgba(0, 0, 0, 0.2)";
    layer.superLayer = PSD.container;
    layer.center();
    return layer;
  };

  rectangle = createRectangle();

  rectangle2 = createRectangle();

  rectangle3 = createRectangle();

  rectangle4 = createRectangle();

  rectangle.states.add({
    centerInvisible: {
      scale: 0.01,
      opacity: 1
    },
    centerBig: {
      scale: 1
    },
    rotated: {
      rotation: 90,
      height: 800,
      y: -40
    }
  });

  rectangle.states.animationOptions = {
    curve: "spring(95, 20, 10)"
  };

  rectangle.states.switchInstant("centerInvisible");

  utils.delay(0.5, function() {
    return rectangle.states["switch"]("centerBig");
  });

  afterRotate = function() {
    rectangle.fadeOut();
    rectangle2.fadeIn();
    rectangle3.fadeIn();
    rectangle2.move(-250, 0);
    rectangle3.move(250, 0);
    utils.delay(1, function() {
      return rectangle2.move(250, 0, "ease-in", 0.3);
    });
    utils.delay(1, function() {
      return rectangle3.move(-250, 0, "ease-in", 0.3);
    });
    return rectangle.off(Events.AnimationEnd, afterRotate);
  };

  utils.delay(1, function() {
    rectangle.states.animationOptions = {
      curve: "spring(150, 22, 1)"
    };
    rectangle.states["switch"]("rotated");
    return rectangle.on(Events.AnimationEnd, afterRotate);
  });

}).call(this);
