// Generated by CoffeeScript 1.7.1
(function() {
  var PSD, afterRotate, bars, createRectangle, rectangle, rectangle2, rectangle3, rectangle4, rectangle5;

  PSD = Framer.Importer.load("imported/google-reel");

  common.storeOriginal(PSD);

  Layer.prototype.move = function(x, y, curve, time) {
    curve = curve || "spring(200, 20, 10)";
    time = time || 0.2;
    return this.animate({
      properties: {
        x: this.x + x,
        y: this.y + y
      },
      curve: curve,
      time: time
    });
  };

  Layer.prototype.fadeOut = function(delay) {
    return this.animate({
      properties: {
        opacity: 0
      },
      curve: 'ease-in',
      delay: delay,
      time: 0.2
    });
  };

  Layer.prototype.fadeIn = function(delay) {
    return this.animate({
      properties: {
        opacity: 1
      },
      curve: 'ease-in',
      delay: delay,
      time: 0.2
    });
  };

  PSD.container.brightness = 0;

  PSD.container.animate({
    properties: {
      brightness: 100
    },
    curve: "linear",
    time: 0.5
  });

  createRectangle = function() {
    var layer;
    layer = new Layer({
      width: 400,
      height: 400,
      backgroundColor: "#fff",
      shadowY: 2,
      shadowBlur: 5,
      borderRadius: "6px",
      opacity: 0
    });
    layer.shadowColor = "rgba(0, 0, 0, 0.2)";
    layer.superLayer = PSD.container;
    layer.center();
    layer.original;
    layer.originalFrame = layer.frame;
    layer.states.add({
      centerInvisible: {
        scale: 0.01,
        opacity: 1
      },
      centerBig: {
        scale: 1,
        opacity: 1,
        height: 400
      },
      rotated: {
        shadowY: 0,
        rotation: 90,
        height: 800,
        y: -40
      },
      unrotated: {
        opacity: 1,
        height: 400,
        y: layer.originalFrame.y,
        shadowY: 0
      },
      barrotated: {
        opacity: 0
      },
      bar: {
        rotation: 0,
        opacity: 1,
        width: 400,
        height: 110
      }
    });
    return layer;
  };

  rectangle = createRectangle();

  rectangle2 = createRectangle();

  rectangle3 = createRectangle();

  rectangle4 = createRectangle();

  rectangle5 = createRectangle();

  rectangle.states.animationOptions = {
    curve: "spring(95, 20, 10)"
  };

  rectangle.states.switchInstant("centerInvisible");

  utils.delay(0.5, function() {
    return rectangle.states["switch"]("centerBig");
  });

  utils.delay(1, function() {
    rectangle.states.animationOptions = {
      curve: "spring(150, 22, 1)"
    };
    rectangle.states["switch"]("rotated");
    return rectangle.on(Events.AnimationEnd, afterRotate);
  });

  afterRotate = function() {
    rectangle.fadeOut();
    rectangle2.fadeIn();
    rectangle3.fadeIn();
    rectangle2.move(-250, 0);
    rectangle3.move(250, 0);
    utils.delay(1, function() {
      rectangle2.move(250, 0, "ease-in", 0.3);
      rectangle3.move(-250, 0, "ease-in", 0.3);
      rectangle2.fadeOut();
      rectangle3.fadeOut();
      rectangle.states["switch"]("unrotated");
      return rectangle.on(Events.AnimationEnd, bars);
    });
    return rectangle.off(Events.AnimationEnd, afterRotate);
  };

  bars = function() {
    rectangle.states["switch"]("barrotated");
    rectangle2.states["switch"]("bar");
    rectangle3.states["switch"]("bar");
    rectangle4.states["switch"]("bar");
    rectangle5.states["switch"]("bar");
    rectangle3.move(0, 100);
    rectangle4.move(0, 200);
    rectangle5.move(0, 300);
    return rectangle.off(Events.AnimationEnd, bars);
  };

}).call(this);
